export const HOME_SET_APPLICATION_COUNTRY = 'HOME_SET_APPLICATION_COUNTRY';
export const HOME_SET_LOCALE = 'HOME_SET_LOCALE';
export const HOME_SET_CURRENCY = 'HOME_SET_CURRENCY';
// AUTO MAINTAINED FILE: DO NOT CHANGE
