// AUTO MAINTAINED FILE: DO NOT CHANGE

export const HOME_FETCH_REDDIT_REACTJS_LIST_BEGIN = 'HOME_FETCH_REDDIT_REACTJS_LIST_BEGIN';
export const HOME_FETCH_REDDIT_REACTJS_LIST_SUCCESS = 'HOME_FETCH_REDDIT_REACTJS_LIST_SUCCESS';
export const HOME_FETCH_REDDIT_REACTJS_LIST_FAILURE = 'HOME_FETCH_REDDIT_REACTJS_LIST_FAILURE';
export const HOME_FETCH_REDDIT_REACTJS_LIST_DISMISS_ERROR = 'HOME_FETCH_REDDIT_REACTJS_LIST_DISMISS_ERROR';
