export const COMMON_GET_TEXT_BEGIN = 'COMMON_GET_TEXT_BEGIN';
export const COMMON_GET_TEXT_SUCCESS = 'COMMON_GET_TEXT_SUCCESS';
export const COMMON_GET_TEXT_FAILURE = 'COMMON_GET_TEXT_FAILURE';
export const COMMON_GET_TEXT_DISMISS_ERROR = 'COMMON_GET_TEXT_DISMISS_ERROR';
