
// NOTE: initialState constant is necessary so that Rekit could auto add initial state when creating async actions.
const initialState = {
    customerAccountTerms: {},
    customerAccount: {},
    customerAccountAllowedPartPayments: [],
    customerAccountBills: [],
    customerAccountCampaignPurchases: [],
    customerAccountCards: [],
    customerAccountTransactions: [],
    customerAccounts: [],
    customerExtraCardHolders: [],
    accountPaymentTerms: {},
    accountLimitRaiseTerms: {},

    // generated
    deleteCustomerAccountPending: false,
    deleteCustomerAccountError: null,
    getCustomerAccountTermsPending: false,
    getCustomerAccountTermsError: null,
    getCustomerAccountPending: false,
    getCustomerAccountError: null,
    getCustomerAccountAllowedPartPaymentsPending: false,
    getCustomerAccountAllowedPartPaymentsError: null,
    getCustomerAccountBillsPending: false,
    getCustomerAccountBillsError: null,
    getCustomerAccountCampaignPurchasesPending: false,
    getCustomerAccountCampaignPurchasesError: null,
    getCustomerAccountCardsPending: false,
    getCustomerAccountCardsError: null,
    getCustomerAccountTransactionsPending: false,
    getCustomerAccountTransactionsError: null,
    getCustomerAccountsPending: false,
    getCustomerAccountsError: null,
    getCustomerExtraCardHoldersPending: false,
    getCustomerExtraCardHoldersError: null,
    getAccountPaymentTermsPending: false,
    getAccountPaymentTermsError: null,
    getAccountLimitRaiseTermsPending: false,
    getAccountLimitRaiseTermsError: null,
    updateCustomerAccountPending: false,
    updateCustomerAccountError: null,
    updateCustomerAccountTransactionPartPaymentPending: false,
    updateCustomerAccountTransactionPartPaymentError: null,
    updateCustomerAccountCardPending: false,
    updateCustomerAccountCardError: null,
};

export default initialState;
